### ISSUE TITLE
minimale Relay-Gebühr senken

### ISSUE THREAD

**Issue by omidsmartdeveloper** [Doichain/doichain-core#3]
**Folgende Gebühren müssen gesenkt werden:**

Die minimal Relay-fee ist überteuert und kann in der doichain.conf gesenkt werden.                 
Wie viel ist eine gute Frage, hier muss man studieren, ob andere Electrumx-Nodes, 
Doicoins verwenden und dann auch die Relaisgebühren erheben. 

Über den Regtest-Node und dem Electrumx das Phänomen nachbilden und untersuchen. 

Wer erhebt die niedrigsten Relay-Gebühren, lässt sich die Doichain-Nodeadresse ermitteln? 
Bitte eine Beispieltransaktion senden! Zuletzt die Prüfung der Möglichkeit, die minimale Relaisgebühr 
vollständig auf 0 zu setzen.

Aufgrund welcher Daten erhält Electrum-DOI seine Gebühren Schätzung (fee estimation).
https://statoshi.info/d/000000020/memory-pool?orgId=1

** Ablauf: Doiworks starten und Snapshot zusammenstellen, Snapshot starten, doichain.conf und die minimale Relay-fee befindet sich im Doichain-Node und ElextrumX-Server. Diese kann hier niedriger eingestellt werden. **

**Hinweis: Was nicht vermischt werden darf ist die Transaktionsfee und die Relay Fee.**

**Comment by stallingerl** [comment]
In Ugly-Bird wurde die minrelaytxfee bereits auf 0,00000001 gesenkt und die fallbackfee liegt bei 0,0002.
Die selben Werte müssen in der doichain.conf auch bei itchy-jellyfish, big-parrot und pink-deer gesetzt werden. Simon bitten die Zugangsdaten mit David und Lena zu teilen.

**Comment by NiKrause** [comment]
Habe minrelaytxfee bereits bei allen 3 anderen Nodes so eingestellt. Das Thema beseitigt anscheinend die leidige Fehlermeldung
der zu hohen Relay Fee bei ElectrumX.  

Die Problematik (eigentlich anderes Issue) warum Transaktionen, die von DoiWallet versendet werden, nicht von den Minern bestätigt werden bleibt.  Die Vermutung, die Mining-Fee sei generell zu niedrig konnte bis jetzt nicht vollständig getestet werden. Erste Tests sprechen aber nicht dafür, dass die Mining-Fee generell zu niedrig ist.

**Comment by NiKrause** [comment]
see https://github.com/Doichain/doichain-core/issues/4
