### ISSUE TITLE
Transaktionen, deren Inputs SegwitAdressen enthalten, werden nicht in die Blöcke aufgenommen

### ISSUE THREAD

**Issue by stallingerl** [Doichain/doichain-core#4]
Transaktionen, die von DoiWallet verschickt werden, sind erfolglos. 

Grund in Doichain-Core wurde bei den Parametern die SegwitHeight zu hoch gesetzt. Erst ab der dort genannten Blockhöhe wäre das Senden von Transaktionen, die SegWit-Adressen als Input haben möglich. 

To do:
Hard Fork mit neuer niedrigerer SegWit height in den Chainparams.

**Comment by stallingerl** [comment]
1. evtl. kann @mrheat bestätigen, dass auf der Adresse auch testcoins einlaufen?
2. David hat jetzt seine Entwicklungsumgung für www.doi.works am laufen und er hat ein Update wie er mittels Doi.Works neue Nodes für testnet starten kann. D.h. ich erwarte hier ein Ergebnis heute bei David. 
3.  So wir einen zweiten Testnet node (auf aktuellem Konsens) mit dem ersten am Laufen haben, erstellen wir ein neues Release in dem das Testnet eine Blockhöhe für die Segwitaktivierung eingestellt wird. 
4. Wir werden dazu einen dritten neuen Testnet mit diesem neuen Release starten. 
5.  Sollte dann der Küchenminer auf diesen Dritten Node (mit dem neuen Konsensus) umeschaltet werden (und sonst erstmal nirgends) 
6. Dann aktualisieren wir Node0 (aktueller Testnet) und Node1 (Doi.Works Noder mit alten Konsensu) manuell (doichain-cli stop, git clone, make, make install, doichaind testnet)
7. Dann warten wir gespannt auf die eingestellte Blockhöhe und schauen ob bei allen 3 Nodes die Blöcke ganz normal eintrudeln. 
8. Segwit-Test mit Electrum-DOI (Testnet) 
9. Segwit-Test mit DoiWallet (Testnet)

**Comment by NiKrause** [comment]
Segwit on Doichain-Core is activated. 
Segwit testet on DoiWallet and Electrum successfully
